Grails will be searched in multiple directories (added the most common by default)

diff --git a/grails b/grails
--- a/grails
+++ b/grails
@@ -1,23 +1,46 @@
 #!/bin/bash
 # Uses the grails version specified in the app properties file. If none found, uses the default installation
+# Grails installations directories must have the name grails-$VERSION (for example, grails-1.3.2) 
 # Diego Toharia - diego@toharia.com
 
-GRAILS_INSTALLATIONS_HOME="$HOME/local"
-DEFAULT_GRAILS_DIR="$GRAILS_INSTALLATIONS_HOME/grails"
-PROPERTIES_FILE=application.properties
+# 
+# Configuration:
+#    - PROPERTIES_FILE: the file with the grails version 
+#      (app.grails.version will be used as property name)
+#    - WHERE_TO_LOOK_FOR_GRAILS_INSTALLATIONS: directories where there may be a grails installation
+#    - DEFAULT_GRAILS_INSTALLATION_NAME: the directory with the default grails installation to use 
+#      when none found in $PROPERTIES_FILEcurrent directory's 
+#
 
-GRAILS_HOME=""
+PROPERTIES_FILE="application.properties"
+WHERE_TO_LOOK_FOR_GRAILS_INSTALLATIONS="$HOME/local /opt /usr/local/"
+DEFAULT_GRAILS_INSTALLATION_NAME="grails"
+
+#
+# Script implementation
+#
+
+# Find the grails installation name
+GRAILS_INSTALLATION_NAME="$DEFAULT_GRAILS_INSTALLATION_NAME"
 if [ -f "$PROPERTIES_FILE" ]; then
 	GRAILS_VERSION=`grep app.grails.version= "$PROPERTIES_FILE" | cut -d'=' -f2`
 	if [ ! -z "$GRAILS_VERSION" ] ; then
-		REQUIRED_GRAILS_DIR="$GRAILS_INSTALLATIONS_HOME/grails-$GRAILS_VERSION"
-		if [ -d "$REQUIRED_GRAILS_DIR" ]; then
-			GRAILS_HOME="$REQUIRED_GRAILS_DIR"
-		fi
-	fi
+		GRAILS_INSTALLATION_NAME="grails-$GRAILS_VERSION"
+    fi
 fi
-if [ -z "$GRAILS_HOME" ] ; then
-	GRAILS_HOME="$DEFAULT_GRAILS_DIR"
+
+# Search the grails installation name in all the possible directories
+IFS=$' '
+GRAILS_HOME=""
+for dir in $WHERE_TO_LOOK_FOR_GRAILS_INSTALLATIONS ; do
+    GRAILS_HOME="$dir/$GRAILS_INSTALLATION_NAME"
+	if [ -d "$GRAILS_HOME" ]; then
+        break
+    fi
+done
+if [ ! -d "$GRAILS_HOME" ] ; then
+    echo "$GRAILS_INSTALLATION_NAME not found in $WHERE_TO_LOOK_FOR_GRAILS_INSTALLATIONS"
+    exit 1
 fi
 export GRAILS_HOME
 
